travis:
  secure:
    BINSTAR_TOKEN: H0xP58tSbiM8P7wtjTyAWH5yj/XnyooRc3zixeAQzBeTfJcM+D36NmvoXqQltLYx1AKln/oSb86N6s6I8JHEgkNhPnQPZd0sBHoyZkvr8AYEWrYi7VcoepKH+RzdNhZSeDjxITSfsJRCQs+gs3lrEGNnwN7FD1zsc6s62DYOa6Hct47rIRpav2jakHHHhCiFOoaCShO8IVvjg368LEP5MWveejeIW8zveWX67aeIsplcNRh1TGcMR/KQc6076yzmKb9aI7hAJkeJQD6CevayToKM5bdZP+XjxEQ+AdOd70X4RA3O6AXo/qjwHspxJ3uIdHncwZhVzTw1UnvDGNYOulZqllSgbOrOQzEev7/IvT7J9hx7ZV1VQ/xFsl0OdKaxOZof8N3SHoJJJooQzU2vIJXJozDTvVhc2Gfn/oKageJReWDR4HJMTCr1AxjOb9WsDSJEvLVOc/D6zj3fr8k6BJEDk6bbewg2pVQiH31Im7VHoco5Z3aEM30DKrKv9jCG09FAWYrNVwXIupdRGRyh/G/fycZ9UVcT0fC5LbUlMxg4b0nOuTIQYMfc8Me00tT6PvqVw1lVWZOQ0e1TDWVF5T8lErqHsMhk7b1mVW5PK2wzJAMnb9OdMyeEYaLQyyGV/cdVZdgh4hhx547oe00ISDx3HDG4xfXO+bv/3b22HHQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
