travis:
  secure:
    BINSTAR_TOKEN: pBEzuqYowf6EgCZQRYxWPeTIGTXBTjycHkRt/YuOvb2CH47cIsm3c1eeTrb1QPeaMckS9t0RF6Y/1FQlAx1I2+x6OCjHFz/AJTm+8LqLYW2wWwKXWYzJmIdJuKLhbSCs9j6YwgLkg2HhG2fsIWbSPnalt7sMC7dy0xsvj24e668UUqpf8CxfEa5vZKqLB033Qe4hkdgl3+xqA++6eia12GiZu9oqX0+4ViHTGPj06oPEId4QX840t0renPFHcDT1flqlxHhjD4exI3L+5BALHWg/a7P9vr76f2f1PtJf6ugC0ktcmHGhS2Xl3jzg8y1skYpoCsBomRwfRYNiVtaW7mH71EdL7fLswBY1ZpeTOQfYzHIZxSwRH2zAmdjLtWFyEu/lYdnLArp2XBZCk1pLLD3fW8FkbXnFGO7mIU946EsZPb9B0jbZEiuIFg/z73VduCFc4adrmEaFcourkfKsYZyv1drsMjc4YrUUrBamM1mT2OlN57bC8SLP3ZY1i/1JuGR6glrgTaMJgYIVYsXwKQHd7DBZJxwbx6CjyftYwmi9dipNLe67LUO4vce6vWeIKRFjagktQegoubZlqFnFzVjz98J80mZUL9a440TGj6PysNVkivO4T/huuedZNCcB+0p4Id6vWUDkQdlg6MAQ2Y92UqRioUijAs+QCYyh2/I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
